/**
 * Account Intelligence Panel — ROADrecon-inspired deep-dive view of a
 * signed-in AAD account, mounted inside the Azure Accounts drawer's
 * "Details" tab.
 *
 * Surfaces seven sections (A–G):
 *
 *   A. Account fingerprint   — guest/member/external detection from
 *                              UPN + mail; sync source (cloud-only vs
 *                              dirsync) via Graph `/me`; home tenant
 *                              fingerprint with copy.
 *   B. Tenant footprint      — every accessible tenant with switch
 *                              button + guest-row highlight.
 *   C. Roles in tenant       — `/me/memberOf` filtered to
 *                              directoryRole; destructive badge for
 *                              Global Admin; per-tenant cache.
 *   D. Token claims decoder  — live ARM + Graph token claims with
 *                              human-friendly explanations and a
 *                              master Hide/Show toggle.
 *   E. Capability matrix     — derived booleans: can list users / can
 *                              reset passwords / can create users /
 *                              can grant roles / can read directory.
 *   F. Quick actions         — navigation shortcuts to Tenant Users,
 *                              Audit Log, EA Billing Manager, plus
 *                              "re-acquire tokens" force-refresh.
 *   G. PRT presence          — indirect probe of whether the browser
 *                              holds a working Primary Refresh Token
 *                              cookie for this account by attempting a
 *                              `prompt=none` authorize through a hidden
 *                              iframe and watching for the redirect.
 *
 * Everything is best-effort: a failed Graph call surfaces an
 * "Unable to determine" Alert inside that section without taking down
 * the rest of the panel. All probes are recorded to the audit log
 * under `account_intelligence_probe` so the operator can correlate the
 * Graph traffic generated by opening this panel.
 *
 * No new shared components, no new npm deps, no edits outside this
 * file + the parent drawer page.
 */
import * as React from "react";
import { AzureLoginAccount } from "../../store/store-types";
export interface AccountIntelligencePanelProps {
    account: AzureLoginAccount;
    /** Optional close-drawer callback fired before quick-action navigation. */
    onClose?: () => void;
}
export declare const AccountIntelligencePanel: React.FC<AccountIntelligencePanelProps>;
//# sourceMappingURL=account-intelligence-panel.d.ts.map