/**
 * Account Intelligence Panel — ROADrecon-inspired deep-dive view of a
 * signed-in AAD account, mounted inside the Azure Accounts drawer's
 * "Details" tab.
 *
 * Surfaces seven sections (A–G):
 *
 *   A. Account fingerprint   — guest/member/external detection from
 *                              UPN + mail; sync source (cloud-only vs
 *                              dirsync) via Graph `/me`; home tenant
 *                              fingerprint with copy.
 *   B. Tenant footprint      — every accessible tenant with switch
 *                              button + guest-row highlight.
 *   C. Roles in tenant       — `/me/memberOf` filtered to
 *                              directoryRole; destructive badge for
 *                              Global Admin; per-tenant cache.
 *   D. Token claims decoder  — live ARM + Graph token claims with
 *                              human-friendly explanations and a
 *                              master Hide/Show toggle.
 *   E. Capability matrix     — derived booleans: can list users / can
 *                              reset passwords / can create users /
 *                              can grant roles / can read directory.
 *   F. Quick actions         — navigation shortcuts to Tenant Users,
 *                              Audit Log, EA Billing Manager, plus
 *                              "re-acquire tokens" force-refresh.
 *   G. PRT presence          — indirect probe of whether the browser
 *                              holds a working Primary Refresh Token
 *                              cookie for this account by attempting a
 *                              `prompt=none` authorize through a hidden
 *                              iframe and watching for the redirect.
 *
 * Everything is best-effort: a failed Graph call surfaces an
 * "Unable to determine" Alert inside that section without taking down
 * the rest of the panel. All probes are recorded to the audit log
 * under `account_intelligence_probe` so the operator can correlate the
 * Graph traffic generated by opening this panel.
 *
 * No new shared components, no new npm deps, no edits outside this
 * file + the parent drawer page.
 */
import * as React from "react";
import {
  AlertCircle,
  AlertTriangle,
  Check,
  Clock,
  Cloud,
  Eye,
  EyeOff,
  FileText,
  Fingerprint,
  Globe,
  HelpCircle,
  KeyRound,
  Loader2,
  RefreshCw,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  UserCheck,
  Users,
  X,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

import {
  decodeJwtClaimsUnsafe,
  getActiveTenant,
  getArmTokenForAccount,
  getGraphTokenForAccount,
} from "../../auth/msal-auth";
import { performTenantSwitch } from "../../auth/perform-tenant-switch";
import { auditLog } from "../../services/audit-log";
import {
  canCreateUsers,
  canResetPasswords,
  getMyDirectoryRoles,
  ROLE_DIRECTORY_READER,
  ROLE_GLOBAL_ADMIN,
  ROLE_GLOBAL_READER,
  ROLE_PRIVILEGED_AUTH_ADMIN,
  ROLE_USER_ADMIN,
} from "../../services";
import { DirectoryRole, TenantInfo } from "../../services/types";
import { useMultiRegionStore } from "../../store/store-context";
import { AzureLoginAccount } from "../../store/store-types";
import { CopyButton, CopyableText } from "../shared/copy-button";
import { InfoTooltip } from "../shared/info-tooltip";

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

/**
 * The Privileged Role Administrator template id — NOT exported by the
 * services barrel (only the Privileged Auth Admin sibling is). Hard-coded
 * here from Microsoft's well-known list to avoid editing
 * `graph-service.ts` (out of scope per the brief).
 *
 * Source:
 * https://learn.microsoft.com/entra/identity/role-based-access-control/permissions-reference#privileged-role-administrator
 */
const ROLE_PRIVILEGED_ROLE_ADMIN = "e8611ab8-c189-46e8-94e1-60213ab1f814";

/**
 * Human descriptions for well-known directory role template ids surfaced
 * in the roles section + capability tooltips. Only the roles this panel
 * actually probes are included — adding new ones is a one-line append.
 */
const ROLE_DESCRIPTIONS: Record<string, string> = {
  [ROLE_GLOBAL_ADMIN]:
    "Global Administrator. Full control over every Microsoft Entra ID feature plus most Microsoft 365 services. Most privileged role in the tenant — every other capability in this panel is granted implicitly.",
  [ROLE_USER_ADMIN]:
    "User Administrator. Manages users and groups, assigns licenses, resets passwords for non-admin users, and creates / deletes users.",
  [ROLE_GLOBAL_READER]:
    "Global Reader. Read-only view of everything Global Admin can see. Cannot make changes but can list users, applications, and policies.",
  [ROLE_DIRECTORY_READER]:
    "Directory Reader. Read basic directory information (users, groups, etc.). Lower-scope variant of Global Reader.",
  [ROLE_PRIVILEGED_AUTH_ADMIN]:
    "Privileged Authentication Administrator. Resets passwords and revokes sessions for any user, including other admins. Manages strong authentication methods.",
  [ROLE_PRIVILEGED_ROLE_ADMIN]:
    "Privileged Role Administrator. Manages role assignments in Entra ID — can grant other admins their roles (including Global Admin).",
};

const TOKEN_CLAIM_DESCRIPTIONS: Record<string, string> = {
  aud: "Audience — which API the token is valid against (ARM, Graph, Batch, etc.).",
  iss: "Issuer — the STS endpoint that minted the token (sts.windows.net/{tid}).",
  iat: "Issued-At — Unix epoch seconds when the token was minted.",
  exp: "Expiry — Unix epoch seconds when the token stops being valid. AAD access tokens are typically 60–90 minutes.",
  nbf: "Not-Before — Unix epoch seconds before which the token is invalid (typically equals `iat`).",
  oid: "Object ID — AAD object id of the user/SPN this token was issued for. Stable across renames.",
  tid: "Tenant ID — Entra ID directory the token was issued in. Differs from the user's home tenant when the user is a guest.",
  scp: "Scope — delegated permissions granted to this token (e.g. user.read).",
  roles: "Roles — application permissions OR app-role claims granted to the principal.",
  wids: "Well-known IDs — directory role template ids the user holds in the issuing tenant. Authoritative source for role-based capability checks (Global Admin = 62e90394-…).",
  app_displayname:
    "App Display Name — public name of the client application that requested this token.",
  appid:
    "App ID — client id of the application that requested this token (e.g. 04b07695-… for the Azure CLI).",
  ipaddr:
    "IP Address — public IP AAD observed the token request coming from. Useful for tracking which network the operator signed in from.",
  xms_cc:
    "Microsoft Extension: Client Capabilities — capabilities the requesting client declared (e.g. CP1 for Continuous Access Evaluation).",
  upn: "User Principal Name — the sign-in name the user authenticated with.",
  preferred_username:
    "Preferred Username — UPN-style value chosen by AAD for display.",
  unique_name: "Unique Name — legacy UPN alias.",
  name: "Display Name — friendly name AAD returned for the user.",
  sub: "Subject — application-specific identifier of the principal. Differs from `oid` per app.",
  amr: "Authentication Methods Reference — which factors were used (pwd, mfa, fido, etc.).",
  acr: "Authentication Context Reference — strength of the authentication (0 = single factor, 1 = MFA).",
  ver: "Token version — AAD JWT format version (1.0 or 2.0).",
};

const TOKEN_CLAIMS_TO_SHOW = [
  "aud",
  "iss",
  "iat",
  "exp",
  "nbf",
  "oid",
  "tid",
  "scp",
  "roles",
  "wids",
  "app_displayname",
  "appid",
  "ipaddr",
  "xms_cc",
  "amr",
  "acr",
  "ver",
] as const;

type AudienceBucket = "arm" | "graph" | "batch" | "unknown";

function classifyAudience(rawAud: string): AudienceBucket {
  const a = (rawAud ?? "").toLowerCase();
  if (
    a.includes("management.azure.com") ||
    a.includes("management.core.windows.net") ||
    a === "797f4846-ba00-4fd7-ba43-dac1f8f63013"
  ) {
    return "arm";
  }
  if (
    a.includes("graph.microsoft.com") ||
    a === "00000003-0000-0000-c000-000000000000"
  ) {
    return "graph";
  }
  if (
    a.includes("batch.core.windows.net") ||
    a === "ddbf3205-c6bd-46ae-8127-60eb93363864"
  ) {
    return "batch";
  }
  return "unknown";
}

function audienceBadgeVariant(
  audience: AudienceBucket,
): "success" | "info" | "warning" | "secondary" {
  if (audience === "arm") return "success";
  if (audience === "graph") return "info";
  if (audience === "batch") return "warning";
  return "secondary";
}

function audienceLabel(audience: AudienceBucket): string {
  if (audience === "arm") return "ARM";
  if (audience === "graph") return "Graph";
  if (audience === "batch") return "Batch";
  return "Other";
}

/**
 * Resolve the active tenant id for an account across the three sources of
 * truth (per-account override → msal-cached → home).
 */
function resolveActiveTenantId(acct: AzureLoginAccount): string {
  return (
    acct.activeTenantId ??
    getActiveTenant(acct.homeAccountId) ??
    acct.tenantId
  );
}

/**
 * Pull the domain out of a UPN or mail address. Returns the empty
 * string when the value doesn't look like an email.
 */
function domainFromAddress(value: string | undefined | null): string {
  if (!value) return "";
  const at = value.lastIndexOf("@");
  if (at < 0) return "";
  return value.slice(at + 1).toLowerCase();
}

/**
 * Detect whether a UPN looks like a B2B guest (has the `#EXT#@` marker)
 * AND whether the home-tenant suffix differs from the mail suffix.
 */
interface AccountTypeFingerprint {
  type: "Member" | "Guest" | "External" | "Unknown";
  reason: string;
  /** UPN-side domain (what AAD recorded). */
  upnDomain: string;
  /** Mail-side domain (what the user actually owns). */
  mailDomain: string;
  /** True when the UPN matches the `…#EXT#@…` B2B pattern. */
  hasExtMarker: boolean;
}

function fingerprintAccountType(
  account: AzureLoginAccount,
  tenants: TenantInfo[] | undefined,
  meResponse: GraphMeResponse | null,
): AccountTypeFingerprint {
  const upn = account.username ?? "";
  const upnDomain = domainFromAddress(upn);
  const mail = meResponse?.mail ?? null;
  const mailDomain = domainFromAddress(mail);
  const hasExtMarker = /#ext#@/i.test(upn);

  // Graph's own `userType` claim is the canonical answer when we got it.
  const userType = meResponse?.userType?.toLowerCase();
  if (userType === "guest") {
    return {
      type: "Guest",
      reason:
        "Microsoft Graph reports userType = Guest. The account was invited to this tenant from another directory.",
      upnDomain,
      mailDomain,
      hasExtMarker,
    };
  }
  if (userType === "member" && !hasExtMarker) {
    return {
      type: "Member",
      reason:
        "Microsoft Graph reports userType = Member and the UPN is native to the tenant.",
      upnDomain,
      mailDomain,
      hasExtMarker,
    };
  }

  // Fall back to UPN-pattern heuristics when /me failed or returned
  // partial data.
  if (hasExtMarker) {
    return {
      type: "Guest",
      reason:
        "UPN contains the B2B `#EXT#@` marker AAD appends to invited accounts. The mail domain shown is the user's home directory.",
      upnDomain,
      mailDomain,
      hasExtMarker,
    };
  }

  // Find the home tenant's default domain to compare against the UPN.
  const homeTenant = tenants?.find((t) => t.tenantId === account.tenantId);
  const homeDomain = (homeTenant?.defaultDomain ?? "").toLowerCase();
  if (
    homeDomain &&
    upnDomain &&
    !upnDomain.endsWith(homeDomain) &&
    !homeDomain.endsWith(upnDomain) &&
    upnDomain !== homeDomain
  ) {
    return {
      type: "External",
      reason: `UPN domain (${upnDomain}) does not match the home tenant's default domain (${homeDomain}). May be a federated account or a guest whose UPN was rewritten.`,
      upnDomain,
      mailDomain,
      hasExtMarker,
    };
  }
  if (
    mailDomain &&
    upnDomain &&
    mailDomain !== upnDomain
  ) {
    return {
      type: "External",
      reason: `Mail domain (${mailDomain}) differs from UPN domain (${upnDomain}). The account likely originated elsewhere.`,
      upnDomain,
      mailDomain,
      hasExtMarker,
    };
  }
  return {
    type: "Member",
    reason:
      "UPN does not contain a B2B marker and the mail / UPN domains agree. Best-effort heuristic — Microsoft Graph `/me` did not return a definitive `userType`.",
    upnDomain,
    mailDomain,
    hasExtMarker,
  };
}

interface SyncSourceFingerprint {
  source: "Cloud-only" | "On-prem synced" | "Unknown";
  reason: string;
  lastSyncIso?: string;
}

function fingerprintSyncSource(
  meResponse: GraphMeResponse | null,
): SyncSourceFingerprint {
  if (!meResponse) {
    return {
      source: "Unknown",
      reason:
        "Microsoft Graph `/me` did not return data — the panel cannot read `onPremisesSyncEnabled`. Re-acquire the Graph token if this persists.",
    };
  }
  if (meResponse.onPremisesSyncEnabled === true) {
    return {
      source: "On-prem synced",
      reason:
        "Graph reports `onPremisesSyncEnabled = true` — the account is mastered in on-premises Active Directory and synced via Entra Connect.",
      lastSyncIso: meResponse.onPremisesLastSyncDateTime ?? undefined,
    };
  }
  if (
    meResponse.onPremisesSyncEnabled === false ||
    meResponse.onPremisesSyncEnabled == null
  ) {
    return {
      source: "Cloud-only",
      reason:
        "Graph did not report `onPremisesSyncEnabled = true` — the account is mastered in Entra ID directly (no Entra Connect mirror).",
    };
  }
  return {
    source: "Unknown",
    reason: "Unexpected value for onPremisesSyncEnabled.",
  };
}

/**
 * Subset of `/me` fields this panel cares about. Kept narrow so we can
 * pull only what we need (`$select`) and so the typing is stable when
 * AAD adds new fields.
 */
interface GraphMeResponse {
  id?: string;
  userPrincipalName?: string;
  mail?: string | null;
  userType?: string;
  onPremisesSyncEnabled?: boolean | null;
  onPremisesLastSyncDateTime?: string | null;
  onPremisesImmutableId?: string | null;
  accountEnabled?: boolean;
  givenName?: string | null;
  surname?: string | null;
  preferredLanguage?: string | null;
}

async function probeGraphMe(
  tenantId: string,
  accessToken: string,
): Promise<GraphMeResponse> {
  const select = [
    "id",
    "userPrincipalName",
    "mail",
    "userType",
    "onPremisesSyncEnabled",
    "onPremisesLastSyncDateTime",
    "onPremisesImmutableId",
    "accountEnabled",
    "givenName",
    "surname",
    "preferredLanguage",
  ].join(",");
  const url = `https://graph.microsoft.com/v1.0/me?$select=${select}`;
  const resp = await fetch(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      Accept: "application/json",
    },
  });
  if (!resp.ok) {
    let detail = `${resp.status}`;
    try {
      const body = (await resp.json()) as {
        error?: { message?: string };
      };
      if (body.error?.message) detail = `${resp.status}: ${body.error.message}`;
    } catch {
      /* body not JSON — ignore */
    }
    throw new Error(`Graph /me failed: ${detail}`);
  }
  const data = (await resp.json()) as Record<string, unknown>;
  return {
    id: typeof data.id === "string" ? data.id : undefined,
    userPrincipalName:
      typeof data.userPrincipalName === "string"
        ? data.userPrincipalName
        : undefined,
    mail:
      typeof data.mail === "string"
        ? data.mail
        : data.mail === null
          ? null
          : undefined,
    userType: typeof data.userType === "string" ? data.userType : undefined,
    onPremisesSyncEnabled:
      typeof data.onPremisesSyncEnabled === "boolean"
        ? data.onPremisesSyncEnabled
        : data.onPremisesSyncEnabled === null
          ? null
          : undefined,
    onPremisesLastSyncDateTime:
      typeof data.onPremisesLastSyncDateTime === "string"
        ? data.onPremisesLastSyncDateTime
        : null,
    onPremisesImmutableId:
      typeof data.onPremisesImmutableId === "string"
        ? data.onPremisesImmutableId
        : null,
    accountEnabled:
      typeof data.accountEnabled === "boolean"
        ? data.accountEnabled
        : undefined,
    givenName: typeof data.givenName === "string" ? data.givenName : null,
    surname: typeof data.surname === "string" ? data.surname : null,
    preferredLanguage:
      typeof data.preferredLanguage === "string"
        ? data.preferredLanguage
        : null,
  };
}

/**
 * Format a unix-epoch-seconds value as "in 14m" / "12m ago", with a
 * tooltip-friendly absolute fallback. Returns "—" on invalid input.
 */
function formatEpoch(value: number | undefined): string {
  if (!value || !Number.isFinite(value)) return "—";
  const deltaMs = value * 1000 - Date.now();
  const absMin = Math.abs(Math.round(deltaMs / 60_000));
  const direction = deltaMs >= 0 ? "in" : "ago";
  if (absMin < 1) return "now";
  if (absMin < 60) return `${direction === "in" ? "in " : ""}${absMin}m${direction === "ago" ? " ago" : ""}`;
  const absHr = Math.round(absMin / 60);
  if (absHr < 24)
    return `${direction === "in" ? "in " : ""}${absHr}h${direction === "ago" ? " ago" : ""}`;
  const absDay = Math.round(absHr / 24);
  return `${direction === "in" ? "in " : ""}${absDay}d${direction === "ago" ? " ago" : ""}`;
}

function isoFromEpoch(value: number | undefined): string {
  if (!value || !Number.isFinite(value)) return "Unknown";
  try {
    return new Date(value * 1000).toISOString();
  } catch {
    return "Unknown";
  }
}

/* ------------------------------------------------------------------ */
/*  Section A — Account fingerprint                                    */
/* ------------------------------------------------------------------ */

interface AccountFingerprintSectionProps {
  account: AzureLoginAccount;
  meResponse: GraphMeResponse | null;
  meError: string | null;
  armTokenIat: number | undefined;
}

const AccountFingerprintSection: React.FC<AccountFingerprintSectionProps> = ({
  account,
  meResponse,
  meError,
  armTokenIat,
}) => {
  const tenants = account.tenants ?? [];
  const fingerprint = fingerprintAccountType(account, tenants, meResponse);
  const sync = fingerprintSyncSource(meResponse);

  const typeBadgeVariant: "success" | "warning" | "destructive" | "info" =
    fingerprint.type === "Member"
      ? "success"
      : fingerprint.type === "Guest"
        ? "warning"
        : fingerprint.type === "External"
          ? "info"
          : "destructive";

  const syncBadgeVariant: "success" | "warning" | "secondary" =
    sync.source === "Cloud-only"
      ? "success"
      : sync.source === "On-prem synced"
        ? "warning"
        : "secondary";

  return (
    <Card className="flex flex-col gap-3 p-4">
      <header className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <UserCheck className="h-4 w-4 text-primary" aria-hidden />
          <h3 className="m-0 text-sm font-semibold">Account fingerprint</h3>
        </div>
        <span className="text-2xs text-muted-foreground">
          Inspired by ROADrecon's user classification.
        </span>
      </header>

      {meError && (
        <Alert variant="warning">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Unable to determine sync source / userType</AlertTitle>
          <AlertDescription>
            <p className="text-2xs">
              Microsoft Graph `/me` returned an error — falling back to
              UPN-pattern heuristics. Re-acquire the Graph token if this
              persists.
            </p>
            <p className="mt-1 break-all font-mono text-[10px] text-muted-foreground">
              {meError}
            </p>
          </AlertDescription>
        </Alert>
      )}

      <div className="flex flex-wrap items-center gap-2">
        <Tooltip>
          <TooltipTrigger asChild>
            <span>
              <Badge variant={typeBadgeVariant} className="gap-1">
                {fingerprint.type === "Guest" ? (
                  <AlertTriangle className="h-3 w-3" aria-hidden />
                ) : (
                  <Check className="h-3 w-3" aria-hidden />
                )}
                {fingerprint.type}
              </Badge>
            </span>
          </TooltipTrigger>
          <TooltipContent side="top" className="max-w-sm">
            {fingerprint.reason}
          </TooltipContent>
        </Tooltip>

        <Tooltip>
          <TooltipTrigger asChild>
            <span>
              <Badge variant={syncBadgeVariant} className="gap-1">
                {sync.source === "On-prem synced" ? (
                  <Server className="h-3 w-3" aria-hidden />
                ) : sync.source === "Cloud-only" ? (
                  <Cloud className="h-3 w-3" aria-hidden />
                ) : (
                  <AlertCircle className="h-3 w-3" aria-hidden />
                )}
                {sync.source}
              </Badge>
            </span>
          </TooltipTrigger>
          <TooltipContent side="top" className="max-w-sm">
            {sync.reason}
            {sync.lastSyncIso && (
              <p className="mt-1 text-[10px] text-muted-foreground">
                Last sync: {sync.lastSyncIso}
              </p>
            )}
          </TooltipContent>
        </Tooltip>

        {fingerprint.hasExtMarker && (
          <Tooltip>
            <TooltipTrigger asChild>
              <span>
                <Badge variant="info" className="gap-1">
                  <Globe className="h-3 w-3" aria-hidden />
                  B2B (#EXT#)
                </Badge>
              </span>
            </TooltipTrigger>
            <TooltipContent side="top" className="max-w-sm">
              The UPN carries the AAD `#EXT#@` marker — the account was
              invited from another directory and AAD rewrote its UPN to
              live in this tenant.
            </TooltipContent>
          </Tooltip>
        )}

        {meResponse?.accountEnabled === false && (
          <Tooltip>
            <TooltipTrigger asChild>
              <span>
                <Badge variant="destructive" className="gap-1">
                  <X className="h-3 w-3" aria-hidden />
                  Disabled
                </Badge>
              </span>
            </TooltipTrigger>
            <TooltipContent side="top">
              Graph reports `accountEnabled = false`. The account would not
              be able to sign in if the existing token expired.
            </TooltipContent>
          </Tooltip>
        )}
      </div>

      <dl className="grid grid-cols-[max-content_1fr] gap-x-4 gap-y-1.5 text-xs">
        <dt className="text-muted-foreground">UPN</dt>
        <dd>
          <CopyableText value={account.username} ariaLabel="Copy UPN" />
        </dd>

        {fingerprint.upnDomain && (
          <>
            <dt className="text-muted-foreground">UPN domain</dt>
            <dd className="font-mono text-foreground">
              {fingerprint.upnDomain}
            </dd>
          </>
        )}

        {fingerprint.mailDomain &&
          fingerprint.mailDomain !== fingerprint.upnDomain && (
            <>
              <dt className="text-muted-foreground flex items-center gap-1">
                Mail domain
                <InfoTooltip
                  content="When the mail domain differs from the UPN domain, the account was likely invited from another directory."
                  ariaLabel="Mail domain help"
                  size={11}
                />
              </dt>
              <dd className="font-mono text-warning">
                {fingerprint.mailDomain}
              </dd>
            </>
          )}

        <dt className="text-muted-foreground flex items-center gap-1">
          Home tenant
          <InfoTooltip
            content="The tenant that owns the account's MSAL session. May differ from the currently-active tenant when this account has multi-tenant access."
            ariaLabel="Home tenant help"
            size={11}
          />
        </dt>
        <dd>
          <CopyableText
            value={account.tenantId}
            mono
            ariaLabel="Copy home tenant id"
          />
        </dd>

        {account.localAccountId && (
          <>
            <dt className="text-muted-foreground flex items-center gap-1">
              Local account id
              <InfoTooltip
                content="AAD object id of this user/SPN in their home tenant — the `oid` claim. Required when this account is referenced cross-tenant (e.g. EA subscription owner)."
                ariaLabel="Local account id help"
                size={11}
              />
            </dt>
            <dd>
              <CopyableText
                value={account.localAccountId}
                mono
                ariaLabel="Copy local account id"
              />
            </dd>
          </>
        )}

        {meResponse?.id && meResponse.id !== account.localAccountId && (
          <>
            <dt className="text-muted-foreground">Graph object id</dt>
            <dd>
              <CopyableText
                value={meResponse.id}
                mono
                ariaLabel="Copy Graph object id"
              />
            </dd>
          </>
        )}

        {meResponse?.onPremisesImmutableId && (
          <>
            <dt className="text-muted-foreground flex items-center gap-1">
              Immutable id
              <InfoTooltip
                content="On-prem AD source anchor (typically base64-encoded objectGUID). Confirms the account is mastered in on-prem AD."
                ariaLabel="Immutable id help"
                size={11}
              />
            </dt>
            <dd>
              <CopyableText
                value={meResponse.onPremisesImmutableId}
                mono
                ariaLabel="Copy immutable id"
              />
            </dd>
          </>
        )}

        <dt className="text-muted-foreground flex items-center gap-1">
          Token issued
          <InfoTooltip
            content="`iat` claim of the live ARM token, i.e. the wall-clock when AAD minted the bearer this WebUI is currently using. Approximates last successful sign-in."
            ariaLabel="iat help"
            size={11}
          />
        </dt>
        <dd>
          <Tooltip>
            <TooltipTrigger asChild>
              <span className="cursor-help text-foreground">
                {armTokenIat
                  ? formatEpoch(armTokenIat).replace(/^in /, "")
                  : "Unknown"}
              </span>
            </TooltipTrigger>
            <TooltipContent side="top">
              {isoFromEpoch(armTokenIat)}
            </TooltipContent>
          </Tooltip>
        </dd>
      </dl>
    </Card>
  );
};

/* ------------------------------------------------------------------ */
/*  Section B — Tenant footprint                                       */
/* ------------------------------------------------------------------ */

interface TenantFootprintSectionProps {
  account: AzureLoginAccount;
  onSwitchTenant: (tenantId: string) => void;
  switchingTenantId: string | null;
}

const TenantFootprintSection: React.FC<TenantFootprintSectionProps> = ({
  account,
  onSwitchTenant,
  switchingTenantId,
}) => {
  const tenants = account.tenants ?? [];
  const activeTenantId = resolveActiveTenantId(account);
  const upnDomain = domainFromAddress(account.username);

  if (tenants.length === 0) {
    return (
      <Card className="flex flex-col gap-2 p-4">
        <header className="flex items-center gap-2">
          <Globe className="h-4 w-4 text-primary" aria-hidden />
          <h3 className="m-0 text-sm font-semibold">Tenant footprint</h3>
        </header>
        <Alert variant="default">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription className="text-2xs">
            Tenant list not yet loaded. Switch to the &ldquo;Tenants&rdquo;
            tab and click &ldquo;Discover tenants&rdquo; to populate this
            section.
          </AlertDescription>
        </Alert>
      </Card>
    );
  }

  return (
    <Card className="flex flex-col gap-3 p-4">
      <header className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Globe className="h-4 w-4 text-primary" aria-hidden />
          <h3 className="m-0 text-sm font-semibold">
            Tenant footprint
            <span className="ml-2 text-2xs font-normal text-muted-foreground">
              {tenants.length} tenant{tenants.length === 1 ? "" : "s"}
            </span>
          </h3>
        </div>
      </header>

      <ScrollArea className="max-h-72">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-border/60 text-left text-2xs uppercase tracking-wider text-muted-foreground">
              <th className="py-1.5 pr-2 font-medium">Tenant</th>
              <th className="py-1.5 pr-2 font-medium">Domain</th>
              <th className="py-1.5 pr-2 font-medium">Subs</th>
              <th className="py-1.5 pr-2 font-medium">Flags</th>
              <th className="py-1.5 pr-2 font-medium text-right"></th>
            </tr>
          </thead>
          <tbody>
            {tenants.map((tenant) => {
              const isHome = tenant.tenantId === account.tenantId;
              const isActive = tenant.tenantId === activeTenantId;
              const tenantDomain = (tenant.defaultDomain ?? "").toLowerCase();
              const isLikelyGuest =
                !!upnDomain &&
                !!tenantDomain &&
                upnDomain !== tenantDomain &&
                !upnDomain.endsWith(tenantDomain) &&
                !tenantDomain.endsWith(upnDomain);
              const subsInTenant = account.subscriptions.filter(
                (s) => s.tenantId === tenant.tenantId,
              ).length;
              const switching = switchingTenantId === tenant.tenantId;

              return (
                <tr
                  key={tenant.tenantId}
                  className={cn(
                    "border-b border-border/30 align-top transition-colors",
                    isActive && "bg-primary/5",
                    isLikelyGuest && !isHome && "bg-warning/5",
                  )}
                >
                  <td className="py-1.5 pr-2">
                    <div className="flex flex-col gap-0.5">
                      <span
                        className="truncate font-medium text-foreground"
                        title={tenant.tenantId}
                      >
                        {tenant.displayName ||
                          tenant.defaultDomain ||
                          tenant.tenantId}
                      </span>
                      <span className="group/copy flex items-center gap-1.5">
                        <span className="truncate font-mono text-[10px] text-muted-foreground">
                          {tenant.tenantId}
                        </span>
                        <CopyButton
                          value={tenant.tenantId}
                          ariaLabel={`Copy tenant id ${tenant.tenantId}`}
                          iconSize={10}
                        />
                      </span>
                    </div>
                  </td>
                  <td className="py-1.5 pr-2">
                    <span
                      className="truncate font-mono text-[11px] text-muted-foreground"
                      title={tenant.defaultDomain ?? ""}
                    >
                      {tenant.defaultDomain ?? "—"}
                    </span>
                  </td>
                  <td className="py-1.5 pr-2 tabular-nums">
                    {isActive ? (
                      <span className="text-foreground">{subsInTenant}</span>
                    ) : (
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <span className="cursor-help text-muted-foreground">
                            —
                          </span>
                        </TooltipTrigger>
                        <TooltipContent side="top" className="max-w-xs">
                          Switch to this tenant to fetch its subscriptions.
                          Cross-tenant subs only become visible after a
                          switch.
                        </TooltipContent>
                      </Tooltip>
                    )}
                  </td>
                  <td className="py-1.5 pr-2">
                    <div className="flex flex-wrap gap-1">
                      {isHome && (
                        <Badge variant="info" className="px-1 py-0">
                          Home
                        </Badge>
                      )}
                      {isActive && (
                        <Badge variant="success" className="px-1 py-0">
                          Active
                        </Badge>
                      )}
                      {isLikelyGuest && !isHome && (
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <span>
                              <Badge
                                variant="warning"
                                className="gap-1 px-1 py-0"
                              >
                                <AlertTriangle
                                  className="h-3 w-3"
                                  aria-hidden
                                />
                                Guest
                              </Badge>
                            </span>
                          </TooltipTrigger>
                          <TooltipContent side="top" className="max-w-sm">
                            UPN domain ({upnDomain}) does not match this
                            tenant&apos;s default domain ({tenantDomain}).
                            The account is most likely a B2B guest in this
                            tenant.
                          </TooltipContent>
                        </Tooltip>
                      )}
                    </div>
                  </td>
                  <td className="py-1.5 pr-1 text-right">
                    {isActive ? (
                      <span className="text-2xs text-muted-foreground">
                        (current)
                      </span>
                    ) : (
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => onSwitchTenant(tenant.tenantId)}
                        disabled={switchingTenantId !== null}
                        aria-label={`Switch to ${tenant.displayName ?? tenant.tenantId}`}
                      >
                        {switching ? (
                          <Loader2 className="h-3 w-3 animate-spin motion-reduce:animate-none" />
                        ) : (
                          <RefreshCw className="h-3 w-3" aria-hidden />
                        )}
                        Switch
                      </Button>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </ScrollArea>
    </Card>
  );
};

/* ------------------------------------------------------------------ */
/*  Section C — Roles in current tenant                                */
/* ------------------------------------------------------------------ */

interface RolesSectionProps {
  roles: DirectoryRole[] | null;
  rolesLoading: boolean;
  rolesError: string | null;
  onReprobe: () => void;
}

const RolesSection: React.FC<RolesSectionProps> = ({
  roles,
  rolesLoading,
  rolesError,
  onReprobe,
}) => {
  const hasGlobalAdmin = roles?.some(
    (r) => r.roleTemplateId === ROLE_GLOBAL_ADMIN,
  );

  return (
    <Card className="flex flex-col gap-3 p-4">
      <header className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Shield className="h-4 w-4 text-primary" aria-hidden />
          <h3 className="m-0 text-sm font-semibold">
            Directory roles
            <span className="ml-2 text-2xs font-normal text-muted-foreground">
              in active tenant
            </span>
          </h3>
        </div>
        <Button
          type="button"
          variant="ghost"
          size="icon-sm"
          onClick={onReprobe}
          disabled={rolesLoading}
          aria-label="Re-probe directory roles"
        >
          <RefreshCw
            className={cn(
              "h-3.5 w-3.5",
              rolesLoading && "animate-spin motion-reduce:animate-none",
            )}
          />
        </Button>
      </header>

      {rolesError && (
        <Alert variant="warning">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Unable to enumerate directory roles</AlertTitle>
          <AlertDescription className="text-2xs">
            <p>{rolesError}</p>
            <p className="mt-1 text-muted-foreground">
              Most common cause: the account holds no directory role in this
              tenant (Graph returns an empty membership list rather than an
              error), or the Graph token lacks `Directory.Read.All` /
              `User.Read` consent.
            </p>
          </AlertDescription>
        </Alert>
      )}

      {hasGlobalAdmin && (
        <Alert variant="destructive">
          <ShieldAlert className="h-4 w-4" />
          <AlertTitle>Global Administrator detected</AlertTitle>
          <AlertDescription className="text-2xs">
            This account holds the most privileged role in the tenant.
            Every action taken with it is high-blast-radius.
          </AlertDescription>
        </Alert>
      )}

      {rolesLoading && !roles ? (
        <p className="flex items-center gap-2 text-2xs text-muted-foreground">
          <Loader2 className="h-3 w-3 animate-spin motion-reduce:animate-none" />
          Probing /me/memberOf…
        </p>
      ) : roles && roles.length === 0 ? (
        <p className="text-2xs text-muted-foreground">
          This account holds no directory role memberships in the active
          tenant. Capability checks below assume non-admin access.
        </p>
      ) : roles && roles.length > 0 ? (
        <ul role="list" className="flex flex-col gap-1.5">
          {roles.map((role) => {
            const known = ROLE_DESCRIPTIONS[role.roleTemplateId];
            const isHigh =
              role.roleTemplateId === ROLE_GLOBAL_ADMIN ||
              role.roleTemplateId === ROLE_PRIVILEGED_ROLE_ADMIN ||
              role.roleTemplateId === ROLE_PRIVILEGED_AUTH_ADMIN;
            return (
              <li
                key={role.id}
                className="group/copy flex items-start gap-2 rounded border border-border/60 bg-card/50 p-2"
              >
                {isHigh ? (
                  <ShieldAlert
                    className="mt-0.5 h-3.5 w-3.5 shrink-0 text-destructive"
                    aria-hidden
                  />
                ) : (
                  <ShieldCheck
                    className="mt-0.5 h-3.5 w-3.5 shrink-0 text-success"
                    aria-hidden
                  />
                )}
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-1.5">
                    <span className="text-xs font-medium text-foreground">
                      {role.displayName || "(unnamed role)"}
                    </span>
                    {isHigh && (
                      <Badge variant="destructive" className="px-1 py-0">
                        High privilege
                      </Badge>
                    )}
                    {known && (
                      <InfoTooltip
                        content={known}
                        ariaLabel={`What is ${role.displayName}`}
                        size={11}
                      />
                    )}
                  </div>
                  {role.description && (
                    <p className="m-0 mt-0.5 text-2xs leading-snug text-muted-foreground">
                      {role.description}
                    </p>
                  )}
                  <div className="mt-1 flex items-center gap-1.5">
                    <span className="truncate font-mono text-[10px] text-muted-foreground/80">
                      template {role.roleTemplateId}
                    </span>
                    <CopyButton
                      value={role.roleTemplateId}
                      ariaLabel="Copy role template id"
                      iconSize={10}
                    />
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      ) : null}
    </Card>
  );
};

/* ------------------------------------------------------------------ */
/*  Section D — Token claims decoder                                   */
/* ------------------------------------------------------------------ */

interface DecodedToken {
  audience: AudienceBucket;
  rawAudience: string;
  rawToken: string;
  claims: Record<string, unknown>;
}

interface TokenClaimsSectionProps {
  decodedTokens: DecodedToken[];
  tokensLoading: boolean;
  tokensError: string | null;
  showTokens: boolean;
  onToggleShowTokens: () => void;
  onReacquire: () => void;
}

function formatClaimValue(value: unknown): string {
  if (value == null) return "—";
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return value.map((v) => String(v)).join(", ");
  }
  if (typeof value === "object") {
    try {
      return JSON.stringify(value);
    } catch {
      return "[object]";
    }
  }
  return String(value);
}

const TokenClaimsSection: React.FC<TokenClaimsSectionProps> = ({
  decodedTokens,
  tokensLoading,
  tokensError,
  showTokens,
  onToggleShowTokens,
  onReacquire,
}) => {
  return (
    <Card className="flex flex-col gap-3 p-4">
      <header className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <FileText className="h-4 w-4 text-primary" aria-hidden />
          <h3 className="m-0 text-sm font-semibold">
            Token claims
            <span className="ml-2 text-2xs font-normal text-muted-foreground">
              live MSAL tokens
            </span>
          </h3>
        </div>
        <div className="flex items-center gap-1">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={onToggleShowTokens}
            aria-label={
              showTokens ? "Hide raw tokens" : "Show raw tokens"
            }
            className="h-7 gap-1 text-2xs"
          >
            {showTokens ? (
              <>
                <EyeOff className="h-3 w-3" aria-hidden />
                Hide tokens
              </>
            ) : (
              <>
                <Eye className="h-3 w-3" aria-hidden />
                Show tokens
              </>
            )}
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            onClick={onReacquire}
            disabled={tokensLoading}
            aria-label="Re-acquire tokens"
            title="Re-acquire all tokens (force-refresh via MSAL silent)"
          >
            <RefreshCw
              className={cn(
                "h-3.5 w-3.5",
                tokensLoading && "animate-spin motion-reduce:animate-none",
              )}
            />
          </Button>
        </div>
      </header>

      {tokensError && (
        <Alert variant="warning">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Unable to acquire one or more tokens</AlertTitle>
          <AlertDescription className="text-2xs">
            {tokensError}
          </AlertDescription>
        </Alert>
      )}

      {tokensLoading && decodedTokens.length === 0 ? (
        <p className="flex items-center gap-2 text-2xs text-muted-foreground">
          <Loader2 className="h-3 w-3 animate-spin motion-reduce:animate-none" />
          Acquiring tokens via MSAL silent…
        </p>
      ) : decodedTokens.length === 0 ? (
        <p className="text-2xs text-muted-foreground">
          No tokens decoded yet.
        </p>
      ) : (
        <div className="flex flex-col gap-3">
          {decodedTokens.map((decoded, idx) => {
            const exp = Number(decoded.claims.exp ?? 0);
            const iat = Number(decoded.claims.iat ?? 0);
            const expiresInMs = exp ? exp * 1000 - Date.now() : 0;
            const isExpired = exp > 0 && expiresInMs <= 0;
            const isSoon = !isExpired && exp > 0 && expiresInMs < 5 * 60_000;
            return (
              <section
                key={`${decoded.audience}-${idx}`}
                aria-label={`${audienceLabel(decoded.audience)} token`}
                className="flex flex-col gap-2 rounded-md border border-border/60 p-3"
              >
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex flex-wrap items-center gap-1.5">
                    <Badge
                      variant={audienceBadgeVariant(decoded.audience)}
                      className="gap-1"
                    >
                      <KeyRound className="h-3 w-3" aria-hidden />
                      {audienceLabel(decoded.audience)}
                    </Badge>
                    {isExpired ? (
                      <Badge variant="destructive" className="gap-1">
                        <AlertCircle className="h-3 w-3" aria-hidden />
                        Expired
                      </Badge>
                    ) : isSoon ? (
                      <Badge variant="warning" className="gap-1">
                        <Clock className="h-3 w-3" aria-hidden />
                        Expires {formatEpoch(exp)}
                      </Badge>
                    ) : (
                      <Badge variant="success" className="gap-1">
                        <Clock className="h-3 w-3" aria-hidden />
                        Expires {formatEpoch(exp)}
                      </Badge>
                    )}
                    {iat > 0 && (
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <span className="cursor-help text-2xs text-muted-foreground">
                            issued {formatEpoch(iat).replace(/^in /, "")}
                          </span>
                        </TooltipTrigger>
                        <TooltipContent side="top">
                          {isoFromEpoch(iat)}
                        </TooltipContent>
                      </Tooltip>
                    )}
                  </div>
                  {showTokens && (
                    <CopyButton
                      value={decoded.rawToken}
                      ariaLabel={`Copy raw ${audienceLabel(decoded.audience)} token`}
                      alwaysVisible
                      iconSize={12}
                    />
                  )}
                </div>
                <p className="m-0 text-[10px] text-muted-foreground">
                  audience{" "}
                  <span className="break-all font-mono text-foreground/80">
                    {decoded.rawAudience}
                  </span>
                </p>
                <dl className="grid grid-cols-[max-content_1fr] gap-x-3 gap-y-1 text-[11px]">
                  {TOKEN_CLAIMS_TO_SHOW.map((claim) => {
                    const value = decoded.claims[claim];
                    if (value === undefined || value === null) return null;
                    const description = TOKEN_CLAIM_DESCRIPTIONS[claim];
                    const formatted = formatClaimValue(value);
                    const truncated =
                      formatted.length > 120
                        ? `${formatted.slice(0, 120)}…`
                        : formatted;
                    return (
                      <React.Fragment key={claim}>
                        <dt className="flex items-center gap-1 font-mono text-muted-foreground">
                          {claim}
                          {description && (
                            <InfoTooltip
                              content={description}
                              ariaLabel={`What is ${claim}`}
                              size={10}
                            />
                          )}
                        </dt>
                        <dd
                          className="break-all font-mono text-foreground"
                          title={formatted}
                        >
                          {truncated}
                        </dd>
                      </React.Fragment>
                    );
                  })}
                </dl>
              </section>
            );
          })}
        </div>
      )}
    </Card>
  );
};

/* ------------------------------------------------------------------ */
/*  Section E — Capability matrix                                      */
/* ------------------------------------------------------------------ */

interface CapabilityMatrixSectionProps {
  roles: DirectoryRole[] | null;
  rolesLoading: boolean;
}

interface Capability {
  label: string;
  description: string;
  /** Role template ids that grant this capability. */
  grantedBy: string[];
  computeGranted: (roles: DirectoryRole[]) => boolean;
}

const CAPABILITIES: Capability[] = [
  {
    label: "List directory users",
    description:
      "GET /users via Microsoft Graph. Required by the Tenant Users page.",
    grantedBy: [
      ROLE_GLOBAL_ADMIN,
      ROLE_USER_ADMIN,
      ROLE_GLOBAL_READER,
      ROLE_DIRECTORY_READER,
    ],
    computeGranted: (roles) =>
      roles.some(
        (r) =>
          r.roleTemplateId === ROLE_GLOBAL_ADMIN ||
          r.roleTemplateId === ROLE_USER_ADMIN ||
          r.roleTemplateId === ROLE_GLOBAL_READER ||
          r.roleTemplateId === ROLE_DIRECTORY_READER,
      ),
  },
  {
    label: "Reset other users' passwords",
    description:
      "PATCH /users/{id} with passwordProfile. Used by the Tenant Users force-password flow.",
    grantedBy: [
      ROLE_GLOBAL_ADMIN,
      ROLE_USER_ADMIN,
      ROLE_PRIVILEGED_AUTH_ADMIN,
    ],
    computeGranted: (roles) => canResetPasswords(roles),
  },
  {
    label: "Create new users",
    description:
      "POST /users via Microsoft Graph. Used by the User Creator page.",
    grantedBy: [ROLE_GLOBAL_ADMIN, ROLE_USER_ADMIN],
    computeGranted: (roles) => canCreateUsers(roles),
  },
  {
    label: "Grant directory roles",
    description:
      "POST /directoryRoles/{id}/members/$ref. Used to elevate other users into admin roles.",
    grantedBy: [ROLE_GLOBAL_ADMIN, ROLE_PRIVILEGED_ROLE_ADMIN],
    computeGranted: (roles) =>
      roles.some(
        (r) =>
          r.roleTemplateId === ROLE_GLOBAL_ADMIN ||
          r.roleTemplateId === ROLE_PRIVILEGED_ROLE_ADMIN,
      ),
  },
  {
    label: "Read directory (groups, apps, policies)",
    description:
      "Broad read of the directory beyond just users. Required by various enumeration pages.",
    grantedBy: [
      ROLE_GLOBAL_ADMIN,
      ROLE_GLOBAL_READER,
      ROLE_DIRECTORY_READER,
    ],
    computeGranted: (roles) =>
      roles.some(
        (r) =>
          r.roleTemplateId === ROLE_GLOBAL_ADMIN ||
          r.roleTemplateId === ROLE_GLOBAL_READER ||
          r.roleTemplateId === ROLE_DIRECTORY_READER,
      ),
  },
];

const CapabilityMatrixSection: React.FC<CapabilityMatrixSectionProps> = ({
  roles,
  rolesLoading,
}) => {
  return (
    <Card className="flex flex-col gap-3 p-4">
      <header className="flex items-center gap-2">
        <Users className="h-4 w-4 text-primary" aria-hidden />
        <h3 className="m-0 text-sm font-semibold">
          Capability matrix
          <span className="ml-2 text-2xs font-normal text-muted-foreground">
            derived from directory roles
          </span>
        </h3>
      </header>

      {rolesLoading && !roles ? (
        <p className="flex items-center gap-2 text-2xs text-muted-foreground">
          <Loader2 className="h-3 w-3 animate-spin motion-reduce:animate-none" />
          Waiting on role probe…
        </p>
      ) : (
        <ul role="list" className="flex flex-col gap-1">
          {CAPABILITIES.map((cap) => {
            const granted = roles ? cap.computeGranted(roles) : false;
            return (
              <li
                key={cap.label}
                className="flex items-start gap-2.5 rounded border border-border/40 bg-card/40 py-1.5 px-2"
              >
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span
                      className={cn(
                        "mt-0.5 inline-flex h-4 w-4 shrink-0 items-center justify-center rounded-full",
                        granted
                          ? "bg-success/20 text-success"
                          : "bg-destructive/15 text-destructive",
                      )}
                      aria-label={granted ? "Granted" : "Not granted"}
                    >
                      {granted ? (
                        <Check className="h-3 w-3" aria-hidden />
                      ) : (
                        <X className="h-3 w-3" aria-hidden />
                      )}
                    </span>
                  </TooltipTrigger>
                  <TooltipContent side="top" className="max-w-sm">
                    <p className="m-0 text-xs">{cap.description}</p>
                    <p className="mt-1 text-2xs text-muted-foreground">
                      Granted by:{" "}
                      {cap.grantedBy
                        .map(
                          (id) =>
                            // Friendly name based on the known
                            // descriptions table; fall back to GUID.
                            (
                              ROLE_DESCRIPTIONS[id]?.split(".")[0] ?? id
                            ),
                        )
                        .join(" · ")}
                    </p>
                  </TooltipContent>
                </Tooltip>
                <div className="min-w-0 flex-1">
                  <p className="m-0 text-xs font-medium text-foreground">
                    {cap.label}
                  </p>
                  <p className="m-0 text-2xs text-muted-foreground">
                    {cap.description}
                  </p>
                </div>
              </li>
            );
          })}
        </ul>
      )}
      {!rolesLoading && !roles && (
        <p className="text-2xs text-muted-foreground">
          Roles unknown — capability columns assume non-admin. Re-probe
          above if the operator just elevated this account.
        </p>
      )}
    </Card>
  );
};

/* ------------------------------------------------------------------ */
/*  Section G — PRT (Primary Refresh Token) presence                   */
/* ------------------------------------------------------------------ */
/*
 * Browsers cannot read the `x-ms-RefreshTokenCredential` cookie that
 * carries the PRT — it is httpOnly and scoped to `login.microsoftonline.com`,
 * so the inspector is INDIRECT. We probe by:
 *
 *   1. Creating a hidden iframe whose `src` is the AAD authorize endpoint
 *      with `prompt=none&response_mode=query`, `client_id` = Azure CLI
 *      (a public first-party that accepts any redirect inside its
 *      allow-list), and a `redirect_uri` pointing back at the dev server.
 *   2. On the dev-server side the WebUI serves whatever lands at `/`,
 *      so the iframe will navigate to `<origin>/?code=...` (success) or
 *      `<origin>/?error=interaction_required` (no usable PRT).
 *   3. Once the iframe finishes navigating, we read its location and
 *      derive success / failure.
 *
 * Subtleties:
 *   - The iframe's final URL is same-origin (since the redirect_uri is the
 *     dev-server origin), so the `load` event handler CAN read
 *     `iframe.contentWindow.location.href`. AAD's intermediate page is
 *     cross-origin (`login.microsoftonline.com`), so the FIRST `load`
 *     event we see may throw a SecurityError on read — that's expected,
 *     we just wait for the next one.
 *   - We DO NOT use `postMessage` from the redirect target because the
 *     redirect target is the SPA's own index.html — we don't want to
 *     ship a separate hosted endpoint just for this probe. Reading the
 *     iframe URL directly works because the URL becomes same-origin once
 *     AAD has issued its 302 back.
 *   - A 5-second timeout guards against PRT-absent cases where AAD shows
 *     its login UI inside the iframe instead of redirecting. The iframe
 *     stays cross-origin in that case and we never get a readable URL.
 *
 * Result interpretation:
 *   - `code=...` in query → PRT exists and SSO works for this client.
 *   - `error=interaction_required` / `login_required` → PRT missing or
 *     stale; user would need to re-sign-in to refresh it.
 *   - Other error / timeout → "Unable to determine".
 *
 * Important limitation: this is browser-only. There is no DPAPI / TPM
 * access from JS so we cannot read the PRT itself. The probe is
 * specifically "can AAD silently issue a token via prompt=none?", which
 * is a useful PROXY for "does the PRT exist and route to this browser?"
 * but is not authoritative — e.g. CA policies that require step-up MFA
 * on every issuance will surface as `interaction_required` even though
 * the PRT is fine.
 */

type PrtProbeStatus =
  | "idle"
  | "probing"
  | "working"
  | "broken"
  | "unable";

interface PrtProbeResult {
  status: PrtProbeStatus;
  detail: string;
  /** Wall-clock when the probe ended, for "last checked" rendering. */
  endedAt?: number;
}

/**
 * Azure CLI client id — same public app used elsewhere in this file's
 * codebase for ARM access. Accepts redirect URIs on the dev-server
 * `localhost:*` allow-list when registered as a public client.
 */
const PRT_PROBE_CLIENT_ID = "04b07795-8ddb-461a-bbee-02f9e1bf7b46";
const PRT_PROBE_TIMEOUT_MS = 5000;

/**
 * Build the authorize URL used by the iframe probe. Mirror the parameter
 * set MSAL.js would send for an ARM `.default` silent acquire, plus
 * `prompt=none` so AAD never shows UI.
 */
function buildPrtProbeAuthorizeUrl(loginHint: string): string {
  const redirectUri =
    typeof window !== "undefined"
      ? `${window.location.origin}/`
      : "http://localhost/";
  const params = new URLSearchParams({
    response_type: "code",
    client_id: PRT_PROBE_CLIENT_ID,
    scope: "https://management.azure.com/.default",
    response_mode: "query",
    prompt: "none",
    redirect_uri: redirectUri,
  });
  if (loginHint) params.set("login_hint", loginHint);
  // `nonce` is required for `id_token` flows; not needed for code flow
  // but some AAD edge cases still demand it. Cheap to include.
  params.set(
    "nonce",
    `azbm-prt-probe-${Math.random().toString(36).slice(2)}`,
  );
  return `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?${params.toString()}`;
}

/**
 * Drive the iframe probe. Resolves with the final probe status — never
 * rejects. The iframe is removed from the DOM before this returns.
 */
function probePrtPresence(loginHint: string): Promise<PrtProbeResult> {
  return new Promise<PrtProbeResult>((resolve) => {
    if (typeof document === "undefined") {
      resolve({
        status: "unable",
        detail: "Running outside a browser — no DOM available.",
        endedAt: Date.now(),
      });
      return;
    }
    const url = buildPrtProbeAuthorizeUrl(loginHint);
    const iframe = document.createElement("iframe");
    iframe.setAttribute("aria-hidden", "true");
    iframe.setAttribute("tabindex", "-1");
    iframe.style.position = "absolute";
    iframe.style.width = "1px";
    iframe.style.height = "1px";
    iframe.style.opacity = "0";
    iframe.style.pointerEvents = "none";
    iframe.style.border = "0";
    iframe.referrerPolicy = "no-referrer";

    let settled = false;
    const cleanup = (): void => {
      if (timeoutId) clearTimeout(timeoutId);
      iframe.onload = null;
      if (iframe.parentNode) iframe.parentNode.removeChild(iframe);
    };
    const finish = (result: PrtProbeResult): void => {
      if (settled) return;
      settled = true;
      cleanup();
      resolve({ ...result, endedAt: Date.now() });
    };

    const timeoutId = window.setTimeout(() => {
      finish({
        status: "unable",
        detail:
          "No same-origin redirect within the timeout window. AAD likely tried to render its login UI inside the iframe (which we can't read cross-origin). Most often this means the PRT is absent or your tenant requires step-up.",
      });
    }, PRT_PROBE_TIMEOUT_MS);

    iframe.onload = (): void => {
      // The first `load` event will throw on cross-origin URL access
      // (AAD landing page). Once AAD redirects back to our origin the
      // subsequent `load` will succeed. We can't tell apart "still on
      // AAD" vs "finished" without try/catch.
      let finalUrl: string;
      try {
        finalUrl = iframe.contentWindow?.location.href ?? "";
      } catch {
        // Still on a cross-origin page (login.microsoftonline.com) —
        // wait for the next load. If AAD never redirects back the
        // timeout above fires.
        return;
      }
      if (!finalUrl) return;

      let parsed: URL;
      try {
        parsed = new URL(finalUrl);
      } catch {
        finish({
          status: "unable",
          detail: `Iframe ended at an unparseable URL: ${finalUrl}`,
        });
        return;
      }

      // Read params from both query string AND hash — some flows use
      // fragment-mode even when we asked for query.
      const qs = parsed.searchParams;
      const hash = new URLSearchParams(
        parsed.hash.startsWith("#") ? parsed.hash.slice(1) : parsed.hash,
      );
      const code = qs.get("code") ?? hash.get("code");
      const error = qs.get("error") ?? hash.get("error");

      if (code) {
        finish({
          status: "working",
          detail:
            "AAD redirected back with an authorization code — `prompt=none` succeeded, so the browser holds a working PRT cookie (or an equivalent SSO artifact) for this client.",
        });
        return;
      }
      if (error) {
        const known = error === "interaction_required" || error === "login_required";
        finish({
          status: known ? "broken" : "unable",
          detail: known
            ? `AAD returned \`error=${error}\` — no usable PRT. The browser must re-authenticate the user before silent SSO can succeed again.`
            : `AAD returned \`error=${error}\`. This is not the standard interaction-required outcome — most often a CA policy or tenant config issue.`,
        });
        return;
      }
      finish({
        status: "unable",
        detail: `Iframe finished at ${parsed.origin}${parsed.pathname} but no \`code\` or \`error\` parameter was present.`,
      });
    };

    document.body.appendChild(iframe);
    iframe.src = url;
  });
}

interface PrtPresenceSectionProps {
  account: AzureLoginAccount;
  tenantLabel: string;
  activeTenantId: string;
}

const PrtPresenceSection: React.FC<PrtPresenceSectionProps> = ({
  account,
  tenantLabel,
  activeTenantId,
}) => {
  const [result, setResult] = React.useState<PrtProbeResult>({
    status: "idle",
    detail:
      "Click Probe to silently ask AAD for a token via `prompt=none`. The probe runs inside a hidden iframe and never shows UI.",
  });
  const probeCounterRef = React.useRef(0);

  const runProbe = React.useCallback(async () => {
    const myId = ++probeCounterRef.current;
    setResult({
      status: "probing",
      detail:
        "Running `prompt=none` authorize via hidden iframe. Up to 5 s.",
    });
    const next = await probePrtPresence(account.username ?? "");
    // Drop the result if the operator started another probe in the
    // meantime — keeps the UI honest under rapid clicks.
    if (probeCounterRef.current !== myId) return;
    setResult(next);
    auditLog.record({
      actor: account.username || account.homeAccountId,
      action: "account_intelligence_probe",
      target: tenantLabel,
      status: next.status === "working" ? "success" : "failure",
      error: next.status === "working" ? undefined : next.detail,
      details: {
        kind: "prt_presence",
        homeAccountId: account.homeAccountId,
        tenantId: activeTenantId,
        outcome: next.status,
      },
    });
  }, [account.username, account.homeAccountId, tenantLabel, activeTenantId]);

  // Auto-run once when the section mounts so the operator sees a result
  // without an extra click. Only fires when status is still `idle` —
  // mounting via tab-switch won't re-fire.
  React.useEffect(() => {
    if (result.status === "idle") {
      void runProbe();
    }
    // We intentionally don't list `result.status` so re-renders after
    // the first probe don't re-trigger. Auto-probe is a "first mount"
    // behavior only.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const isProbing = result.status === "probing";

  return (
    <Card className="flex flex-col gap-3 p-4">
      <header className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Fingerprint className="h-4 w-4 text-primary" aria-hidden />
          <h3 className="m-0 text-sm font-semibold">
            PRT presence
            <span className="ml-2 text-2xs font-normal text-muted-foreground">
              browser SSO probe
            </span>
          </h3>
        </div>
        <Button
          type="button"
          variant="ghost"
          size="icon-sm"
          onClick={() => void runProbe()}
          disabled={isProbing}
          aria-label="Re-probe PRT presence"
          title="Re-run the prompt=none authorize probe"
        >
          <RefreshCw
            className={cn(
              "h-3.5 w-3.5",
              isProbing && "animate-spin motion-reduce:animate-none",
            )}
          />
        </Button>
      </header>

      <div className="flex flex-wrap items-center gap-2">
        {result.status === "working" && (
          <Badge variant="success" className="gap-1">
            <Check className="h-3 w-3" aria-hidden />
            Working
          </Badge>
        )}
        {result.status === "broken" && (
          <Badge variant="destructive" className="gap-1">
            <X className="h-3 w-3" aria-hidden />
            Broken
          </Badge>
        )}
        {result.status === "probing" && (
          <Badge variant="info" className="gap-1">
            <Loader2 className="h-3 w-3 animate-spin motion-reduce:animate-none" />
            Probing
          </Badge>
        )}
        {result.status === "unable" && (
          <Badge variant="warning" className="gap-1">
            <AlertTriangle className="h-3 w-3" aria-hidden />
            Unable to determine
          </Badge>
        )}
        {result.status === "idle" && (
          <Badge variant="secondary" className="gap-1">
            <HelpCircle className="h-3 w-3" aria-hidden />
            Not probed
          </Badge>
        )}
        <span className="text-2xs text-muted-foreground">
          via hidden iframe · prompt=none · client_id Azure CLI
        </span>
      </div>

      <p className="m-0 text-2xs leading-snug text-muted-foreground">
        {result.detail}
      </p>

      {result.status === "broken" && (
        <Alert variant="warning">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Browser cannot SSO silently</AlertTitle>
          <AlertDescription className="text-2xs">
            <p>
              AAD requires interaction before it will issue a token to this
              account in this browser. Token re-acquisition will pop the
              MSAL login window the next time the operator hits a Graph or
              ARM call that needs a fresh bearer.
            </p>
            <p className="mt-1 text-muted-foreground">
              If the operator just logged in and still sees this, check
              that third-party cookies are allowed for{" "}
              <span className="font-mono">login.microsoftonline.com</span>{" "}
              from this origin and that any browser tracking-protection
              isolation isn&apos;t partitioning the cookie jar.
            </p>
          </AlertDescription>
        </Alert>
      )}

      {result.status === "unable" && (
        <Alert variant="default">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Probe was inconclusive</AlertTitle>
          <AlertDescription className="text-2xs">
            <p>
              Most often AAD chose to render its login UI inside the
              iframe (which we cannot read across origins). This is what
              happens when the PRT is absent AND the tenant&apos;s CA
              policy forbids silent token issuance for this app, OR when
              browser cookie-isolation is partitioning the
              login.microsoftonline.com cookie jar.
            </p>
            <p className="mt-1 text-muted-foreground">
              Note: this probe is browser-only. We cannot read the
              underlying PRT cookie from JS (httpOnly + cross-origin), so
              the result is a PROXY signal — &ldquo;does silent SSO
              work?&rdquo; rather than &ldquo;is the PRT bytes-present?&rdquo;
            </p>
          </AlertDescription>
        </Alert>
      )}

      {result.endedAt && (
        <p className="m-0 text-[10px] text-muted-foreground">
          Last checked {new Date(result.endedAt).toLocaleTimeString()}.
        </p>
      )}
    </Card>
  );
};

/* ------------------------------------------------------------------ */
/*  Section F — Quick actions                                          */
/* ------------------------------------------------------------------ */

interface QuickActionsSectionProps {
  onNavigate: (path: string) => void;
  onReacquireTokens: () => void;
  tokensLoading: boolean;
}

const QuickActionsSection: React.FC<QuickActionsSectionProps> = ({
  onNavigate,
  onReacquireTokens,
  tokensLoading,
}) => {
  return (
    <Card className="flex flex-col gap-2 p-4">
      <header className="flex items-center gap-2">
        <RefreshCw className="h-4 w-4 text-primary" aria-hidden />
        <h3 className="m-0 text-sm font-semibold">Quick actions</h3>
      </header>
      <div className="flex flex-wrap gap-2">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => onNavigate("/tenant-users")}
        >
          <Users className="h-3.5 w-3.5" aria-hidden />
          Open Tenant Users
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => onNavigate("/audit-log")}
        >
          <FileText className="h-3.5 w-3.5" aria-hidden />
          Open Audit Log
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => onNavigate("/ea-billing-manager")}
        >
          <KeyRound className="h-3.5 w-3.5" aria-hidden />
          Open EA Billing Manager
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={onReacquireTokens}
          disabled={tokensLoading}
          loading={tokensLoading}
        >
          {!tokensLoading && (
            <RefreshCw className="h-3.5 w-3.5" aria-hidden />
          )}
          Re-acquire all tokens
        </Button>
      </div>
      <p className="m-0 mt-1 text-2xs text-muted-foreground">
        Quick actions navigate to other pages; the audit log is not
        pre-filtered (filter manually with the actor dropdown there).
      </p>
    </Card>
  );
};

/* ------------------------------------------------------------------ */
/*  Main panel                                                         */
/* ------------------------------------------------------------------ */

export interface AccountIntelligencePanelProps {
  account: AzureLoginAccount;
  /** Optional close-drawer callback fired before quick-action navigation. */
  onClose?: () => void;
}

export const AccountIntelligencePanel: React.FC<
  AccountIntelligencePanelProps
> = ({ account, onClose }) => {
  const navigate = useNavigate();
  const store = useMultiRegionStore();
  const activeTenantId = resolveActiveTenantId(account);
  const tenantLabel =
    account.tenants?.find((t) => t.tenantId === activeTenantId)?.displayName ??
    activeTenantId;

  /* ---- Token state ---- */
  const [armToken, setArmToken] = React.useState<string | null>(null);
  const [graphToken, setGraphToken] = React.useState<string | null>(null);
  const [tokensLoading, setTokensLoading] = React.useState(false);
  const [tokensError, setTokensError] = React.useState<string | null>(null);
  const [showTokens, setShowTokens] = React.useState(false);

  /* ---- Graph /me state ---- */
  const [meResponse, setMeResponse] = React.useState<GraphMeResponse | null>(
    null,
  );
  const [meError, setMeError] = React.useState<string | null>(null);

  /* ---- Roles state (cached per tenant) ---- */
  const rolesCacheRef = React.useRef<Map<string, DirectoryRole[]>>(new Map());
  const [roles, setRoles] = React.useState<DirectoryRole[] | null>(null);
  const [rolesLoading, setRolesLoading] = React.useState(false);
  const [rolesError, setRolesError] = React.useState<string | null>(null);
  const [rolesProbeNonce, setRolesProbeNonce] = React.useState(0);

  /* ---- Tenant switching state ---- */
  const [switchingTenantId, setSwitchingTenantId] = React.useState<
    string | null
  >(null);
  const switchAbortRef = React.useRef<AbortController | null>(null);

  /* ---- Cancel inflight on unmount ---- */
  React.useEffect(() => {
    return () => {
      switchAbortRef.current?.abort();
    };
  }, []);

  /**
   * Acquire ARM + Graph tokens silently via MSAL. Called on mount and
   * whenever the operator clicks "Re-acquire". Best-effort: a single
   * failure shouldn't block decoding the one that succeeded.
   */
  const fetchTokens = React.useCallback(async () => {
    setTokensLoading(true);
    setTokensError(null);
    const errors: string[] = [];
    try {
      const [armResult, graphResult] = await Promise.allSettled([
        getArmTokenForAccount(account.homeAccountId, activeTenantId),
        getGraphTokenForAccount(account.homeAccountId, activeTenantId),
      ]);
      if (armResult.status === "fulfilled") {
        setArmToken(armResult.value);
      } else {
        const msg =
          armResult.reason instanceof Error
            ? armResult.reason.message
            : String(armResult.reason);
        errors.push(`ARM: ${msg}`);
      }
      if (graphResult.status === "fulfilled") {
        setGraphToken(graphResult.value);
      } else {
        const msg =
          graphResult.reason instanceof Error
            ? graphResult.reason.message
            : String(graphResult.reason);
        errors.push(`Graph: ${msg}`);
      }
      if (errors.length > 0) setTokensError(errors.join(" · "));
    } finally {
      setTokensLoading(false);
    }
  }, [account.homeAccountId, activeTenantId]);

  React.useEffect(() => {
    void fetchTokens();
  }, [fetchTokens]);

  /**
   * After the Graph token lands, probe /me for the canonical userType +
   * onPremisesSyncEnabled. Every probe writes an audit entry.
   */
  React.useEffect(() => {
    if (!graphToken) return;
    let cancelled = false;
    (async () => {
      try {
        const me = await probeGraphMe(activeTenantId, graphToken);
        if (cancelled) return;
        setMeResponse(me);
        setMeError(null);
        auditLog.record({
          actor: account.username || account.homeAccountId,
          action: "account_intelligence_probe",
          target: tenantLabel,
          status: "success",
          details: {
            kind: "graph_me",
            homeAccountId: account.homeAccountId,
            tenantId: activeTenantId,
            userType: me.userType,
            onPremisesSyncEnabled: me.onPremisesSyncEnabled,
          },
        });
      } catch (e: unknown) {
        if (cancelled) return;
        const msg = e instanceof Error ? e.message : String(e);
        setMeError(msg);
        setMeResponse(null);
        auditLog.record({
          actor: account.username || account.homeAccountId,
          action: "account_intelligence_probe",
          target: tenantLabel,
          status: "failure",
          error: msg,
          details: {
            kind: "graph_me",
            homeAccountId: account.homeAccountId,
            tenantId: activeTenantId,
          },
        });
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [
    graphToken,
    activeTenantId,
    account.homeAccountId,
    account.username,
    tenantLabel,
  ]);

  /**
   * Probe directory roles for the active tenant. Cached per tenantId so
   * a tab switch back to the same tenant doesn't re-hit Graph. The
   * `rolesProbeNonce` lets the operator force a re-probe.
   */
  React.useEffect(() => {
    if (!activeTenantId) return;
    const cached = rolesCacheRef.current.get(activeTenantId);
    if (cached && rolesProbeNonce === 0) {
      setRoles(cached);
      setRolesLoading(false);
      setRolesError(null);
      return;
    }
    let cancelled = false;
    setRolesLoading(true);
    setRolesError(null);
    (async () => {
      try {
        const token = await getGraphTokenForAccount(
          account.homeAccountId,
          activeTenantId,
        );
        const result = await getMyDirectoryRoles(activeTenantId, token);
        if (cancelled) return;
        rolesCacheRef.current.set(activeTenantId, result);
        setRoles(result);
        auditLog.record({
          actor: account.username || account.homeAccountId,
          action: "account_intelligence_probe",
          target: tenantLabel,
          status: "success",
          details: {
            kind: "directory_roles",
            homeAccountId: account.homeAccountId,
            tenantId: activeTenantId,
            roleCount: result.length,
            roleTemplateIds: result.map((r) => r.roleTemplateId),
          },
        });
      } catch (e: unknown) {
        if (cancelled) return;
        const msg = e instanceof Error ? e.message : String(e);
        setRolesError(msg);
        setRoles(null);
        auditLog.record({
          actor: account.username || account.homeAccountId,
          action: "account_intelligence_probe",
          target: tenantLabel,
          status: "failure",
          error: msg,
          details: {
            kind: "directory_roles",
            homeAccountId: account.homeAccountId,
            tenantId: activeTenantId,
          },
        });
      } finally {
        if (!cancelled) setRolesLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [
    activeTenantId,
    account.homeAccountId,
    account.username,
    tenantLabel,
    rolesProbeNonce,
  ]);

  /* ---- Decoded tokens (memo so we don't recompute every render) ---- */
  const decodedTokens = React.useMemo<DecodedToken[]>(() => {
    const out: DecodedToken[] = [];
    const ingest = (raw: string | null) => {
      if (!raw) return;
      const claims = decodeJwtClaimsUnsafe(raw);
      if (!claims) return;
      const rawAud = String(claims.aud ?? "");
      out.push({
        audience: classifyAudience(rawAud),
        rawAudience: rawAud,
        rawToken: raw,
        claims,
      });
    };
    ingest(armToken);
    ingest(graphToken);
    return out;
  }, [armToken, graphToken]);

  const armTokenIat = React.useMemo(() => {
    if (!armToken) return undefined;
    const claims = decodeJwtClaimsUnsafe(armToken);
    if (!claims) return undefined;
    const iat = Number(claims.iat);
    return Number.isFinite(iat) && iat > 0 ? iat : undefined;
  }, [armToken]);

  /* ---- Tenant-switch handler (delegates to shared performTenantSwitch) ---- */
  const handleSwitchTenant = React.useCallback(
    async (tenantId: string) => {
      if (switchingTenantId !== null) return;
      switchAbortRef.current?.abort();
      const controller = new AbortController();
      switchAbortRef.current = controller;
      setSwitchingTenantId(tenantId);
      try {
        await performTenantSwitch(account, tenantId, store, {
          source: "drawer",
          signal: controller.signal,
          onSuccess: () => {
            // Force a re-probe in the new tenant. Bumping nonce
            // bypasses the per-tenant role cache.
            setRolesProbeNonce((n) => n + 1);
          },
        });
      } finally {
        if (switchAbortRef.current === controller) {
          switchAbortRef.current = null;
        }
        setSwitchingTenantId(null);
      }
    },
    [account, store, switchingTenantId],
  );

  const handleNavigate = React.useCallback(
    (path: string) => {
      onClose?.();
      navigate(path);
    },
    [navigate, onClose],
  );

  const handleToggleShowTokens = React.useCallback(() => {
    setShowTokens((v) => !v);
  }, []);

  const handleReprobeRoles = React.useCallback(() => {
    rolesCacheRef.current.delete(activeTenantId);
    setRolesProbeNonce((n) => n + 1);
  }, [activeTenantId]);

  const handleReacquireTokens = React.useCallback(() => {
    void fetchTokens();
  }, [fetchTokens]);

  return (
    <div className="flex flex-col gap-3">
      <AccountFingerprintSection
        account={account}
        meResponse={meResponse}
        meError={meError}
        armTokenIat={armTokenIat}
      />
      <TenantFootprintSection
        account={account}
        onSwitchTenant={handleSwitchTenant}
        switchingTenantId={switchingTenantId}
      />
      <RolesSection
        roles={roles}
        rolesLoading={rolesLoading}
        rolesError={rolesError}
        onReprobe={handleReprobeRoles}
      />
      <TokenClaimsSection
        decodedTokens={decodedTokens}
        tokensLoading={tokensLoading}
        tokensError={tokensError}
        showTokens={showTokens}
        onToggleShowTokens={handleToggleShowTokens}
        onReacquire={handleReacquireTokens}
      />
      <CapabilityMatrixSection roles={roles} rolesLoading={rolesLoading} />
      <PrtPresenceSection
        account={account}
        tenantLabel={tenantLabel}
        activeTenantId={activeTenantId}
      />
      <QuickActionsSection
        onNavigate={handleNavigate}
        onReacquireTokens={handleReacquireTokens}
        tokensLoading={tokensLoading}
      />
    </div>
  );
};
